# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

2.2.6


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
vec = np.array([0]*10)
print(vec)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print((vec.size * vec.itemsize))
print(vec.size)
print(vec.itemsize)

80
10
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
ones_vec = np.ones(10)
print(ones_vec)
ones_vec[4]= 0
print(ones_vec)    

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]


In [ ]:
vec = np.array([2]*10)
vec[4] = 5
vec

array([2, 2, 2, 2, 5, 2, 2, 2, 2, 2])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
# np.arange(start, stop, step)
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vec = np.array(vec)
print(vec[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr = np.array([[1,2,3],[1,2,4],[1,2,3]])
print(arr)

[[1 2 3]
 [1 2 4]
 [1 2 3]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
vec = [1,2,0,0,4,0]
non_zero_indices = [i for i, x in enumerate(vec) if x != 0]
print(non_zero_indices)

[0, 1, 4]


In [ ]:
np.nonzero(vec)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.random((3,3,3))

array([[[0.21871625, 0.08698198, 0.1908196 ],
        [0.98675908, 0.59974637, 0.61158809],
        [0.92135907, 0.49639439, 0.12539363]],

       [[0.94950302, 0.38383418, 0.74047112],
        [0.06496823, 0.40152336, 0.822482  ],
        [0.63352145, 0.92834723, 0.973168  ]],

       [[0.28650846, 0.76569885, 0.53213843],
        [0.3378201 , 0.43501854, 0.77550563],
        [0.25266559, 0.22435461, 0.0446232 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.random((10,10,10))
print(np.min(arr))
print(np.max(arr))

0.0014553940110789698
0.9995587129119566


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
x = np.random.random(10)
print(x)
n= int(len(x))
print(n)
np.mean(x)

[0.49759781 0.81393403 0.99871261 0.1037231  0.65866093 0.76114776
 0.26653997 0.81100101 0.77109338 0.41548146]
10


np.float64(0.6097892048234478)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x = np.ones((5,5))
print(x)
x[1:-1, 1:-1] = 0
print("After bordring \n",x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
After bordring 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
x = np.zeros((8,8), dtype = int)
x[1::2, ::2]=1
x[::2,1::2]=1

x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
# The shape of the array
shape = (6, 7, 8)

linear_index = 98

index = np.unravel_index(linear_index, shape)
print(f"The index is: {index}")

The index is: (np.int64(1), np.int64(5), np.int64(2))


In [ ]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr = np.zeros(8)
rep = (3,1)
arr = np.tile(arr, (8,1))
arr[1::2, ::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr = np.random.random((5,5))
min = arr.min()
max = arr.max()
print("Arr- min", arr-min)
print("Max - Min ", max-min)
normalized_arr = (arr - min) / (max - min)
print("Normalized Array:\n", normalized_arr)

Arr- min [[0.54737501 0.10311533 0.37455396 0.52457473 0.94039054]
 [0.19020464 0.77035496 0.94959197 0.64236131 0.05580209]
 [0.54281472 0.         0.62278615 0.09353733 0.96101036]
 [0.73044383 0.7544818  0.24337051 0.71862479 0.22722102]
 [0.7206153  0.35624412 0.7406021  0.59129482 0.05994546]]
Max - Min  0.9610103594607743
Normalized Array:
 [[0.56958284 0.10729887 0.38975018 0.54585752 0.9785436 ]
 [0.19792153 0.80160942 0.98811835 0.66842288 0.05806607]
 [0.56483754 0.         0.64805353 0.09733228 1.        ]
 [0.76007904 0.78509226 0.25324442 0.74778048 0.23643972]
 [0.74985175 0.37069748 0.77064944 0.61528454 0.06237754]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.ones((5, 3))
b = np.ones((3, 2))

Z = np.matmul(a,b)
print("Z Matrix \n",Z)
print("MAtrix A \n",a)
print("Matrix B \n",b)
print("Matrix Multiplication AxB \n")
print(np.dot(a, b))

Z Matrix 
 [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
MAtrix A 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrix B 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix Multiplication AxB 

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(10)
for i in arr:
    if i>3 and i<8:
        arr[i] *= -1
print(arr)
Z  = np.arange(10)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
import numpy as np
print(np.sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.ones(5)
Z**Z


array([1., 1., 1., 1., 1.])

In [ ]:
2 << Z >> 2   # not legal 

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
Z <- Z


array([False, False, False, False, False])

In [ ]:
1j*Z


array([0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j])

In [ ]:
Z/1/1   


array([1., 1., 1., 1., 1.])

In [ ]:
# Z<Z>Z   not Legal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

C:\Program Files\KMSpico\temp\ipykernel_23080\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [ ]:
np.array(0) // np.array(0)

C:\Program Files\KMSpico\temp\ipykernel_23080\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [ ]:
np.array([np.nan]).astype(int).astype(float)

C:\Program Files\KMSpico\temp\ipykernel_23080\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z)

[5.83225541 1.7576009  0.19311399 0.68569562 4.51168485 5.64438086
 8.47861173 2.85066813 2.1209462  0.63281368]


In [ ]:
print(np.abs(Z))

[5.83225541 1.7576009  0.19311399 0.68569562 4.51168485 5.64438086
 8.47861173 2.85066813 2.1209462  0.63281368]


In [ ]:
print(np.copysign(np.ceil(Z), Z))

[10.  1.  9.  4.  6.  5.  3.  7.  1.  5.]


In [ ]:
print(np.copysign(np.ceil(np.abs(Z)), Z))

[10.  1.  9.  4.  6.  5.  3.  7.  1.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
ar1=  np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,8,9,10])
intersection = np.intersect1d(ar1, arr2)
print(intersection)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0


In [ ]:
_ = np.seterr(**defaults)

In [ ]:
z = np.ones(1) / 0
print(z)

[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
import datetime
today = datetime.date.today()   
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)
print("Today:", today, "yesterday:", yesterday, "tomorrow:", tomorrow)

Today: 2025-10-01 yesterday: 2025-09-30 tomorrow: 2025-10-02


In [ ]:
today = np.datetime64('now', 'M')
yest = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomor = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yest,today, tomor

(np.datetime64('2025-09-30'),
 np.datetime64('2025-10'),
 np.datetime64('2025-10-02'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import calendar
y = 2000
m = 8
print(calendar.month(y, m))

    August 2000
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31



In [ ]:
Z = np.arange('2016-07', '2016-09', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31' '2016-08-01' '2016-08-02' '2016-08-03' '2016-08-04'
 '2016-08-05' '2016-08-06' '2016-08-07' '2016-08-08' '2016-08-09'
 '2016-08-10' '2016-08-11' '2016-08-12' '2016-08-13' '2016-08-14'
 '2016-08-15' '2016-08-16' '2016-08-17' '2016-08-18' '2016-08-19'
 '2016-08-20' '2016-08-21' '2016-08-22' '2016-08-23' '2016-08-24'
 '2016-08-25' '2016-08-26' '2016-08-27' '2016-08-28' '2016-08-29'
 '2016-08-30' '2016-08-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = B = np.ones(3)*2
print(A)
print(B)

[1. 1. 1.]
[2. 2. 2.]


In [ ]:
add = np.add(A,B,out=B)
np.divide(A,2,out=B)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-4.5, -4.5, -4.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z)

[0.59545518 2.50158714 1.88042525 2.83095865 1.45568044 8.02619754
 2.26823787 0.68837673 0.14234641 3.21526048]


In [ ]:
# Method 1
print(Z-Z%1)
print(np.floor(Z))
print(Z//1)
print(np.trunc(Z))
print(Z.astype(int))

[0. 2. 1. 2. 1. 8. 2. 0. 0. 3.]
[0. 2. 1. 2. 1. 8. 2. 0. 0. 3.]
[0. 2. 1. 2. 1. 8. 2. 0. 0. 3.]
[0. 2. 1. 2. 1. 8. 2. 0. 0. 3.]
[0 2 1 2 1 8 2 0 0 3]


In [ ]:
50//3

16

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr = np.zeros((5,5))
print(arr)
print("\n After adding the value from 0-4\n")
arr +=np.arange(5)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 After adding the value from 0-4

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
iter = ([x for x in range(10)])
iter


np.fromiter(iter, np.float32)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
x = np.linspace(0, 1, num=10, endpoint=True)
print(x)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.random(10)
print(np.sort(arr))
print(np.sort(arr[::-1]))

[0.0339761  0.12324818 0.20860368 0.23336951 0.27514819 0.40722773
 0.53300602 0.71597473 0.92577875 0.98028573]
[0.0339761  0.12324818 0.20860368 0.23336951 0.27514819 0.40722773
 0.53300602 0.71597473 0.92577875 0.98028573]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
z = np.arange(10)
z = np.add.reduce(z)
print(z)

45


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
X = np.random.randint(0,2,6)
print(X)
Y = np.random.randint(0,2,6)
print(Y)

print(np.isclose(X,Y))
print(np.allclose(X,Y))

[1 1 1 1 0 1]
[1 1 1 1 1 1]
[ True  True  True  True False  True]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
# Importing the NumPy library and aliasing it as 'np'
import numpy as np

# Creating a NumPy array 'x' filled with zeros, containing 10 elements
x = np.zeros(10)

# Setting the 'writeable' flag of the array 'x' to False, making it read-only
x.flags.writeable = False

# Printing a message to test whether the array is read-only or not
print("Test the array is read-only or not:")

# Attempting to change the value of the first element in the array 'x'
print("Try to change the value of the first element:")
# x[0] = 1  # This line will raise an error since the array is read-only 


Test the array is read-only or not:
Try to change the value of the first element:


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
z = np.random.random((10, 2))
z
# extracting  the columns into x and y 
x,y = z[:,0], z[:, 1]
# x, y = z[:, 0], z[:, 1]
print(x)
print(y)

[0.22288323 0.5418671  0.52389908 0.20969488 0.77220383 0.37284371
 0.99301975 0.73307875 0.4960161  0.96691462]
[0.71113321 0.933635   0.60982829 0.69202868 0.56132887 0.47936342
 0.87408431 0.86013997 0.3316416  0.0178758 ]


In [ ]:
# Calculating the Euclidean distance (r) using the formula sqrt(x^2 + y^2)
r = np.sqrt(x**2 + y**2)
print(r)

[0.29782967 0.8903178  0.02217334 0.45019872 1.10988933 0.36488678
 1.16169537 1.05878009 0.85676314 1.1512301 ]


In [ ]:
# Calculating the angles (t) using arctan2() function, which returns the arctangent of y/x in radians
t = np.arctan2(y, x)

# Displaying the calculated Euclidean distances (r)
print(r)

# Displaying the calculated angles (t) in radians
print(t)

[0.29782967 0.8903178  0.02217334 0.45019872 1.10988933 0.36488678
 1.16169537 1.05878009 0.85676314 1.1512301 ]
[1.26707371 1.04492501 0.86104707 1.27657603 0.62856424 0.90974601
 0.72178363 0.864981   0.58934716 0.01848536]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vec = np.random.rand(10)
vec

array([0.76174918, 0.57773819, 0.32201281, 0.36990868, 0.87970263,
       0.87226443, 0.15702999, 0.93338608, 0.75082995, 0.95399876])

In [ ]:
max_val = np.max(vec)
max_val

np.float64(0.9539987589227577)

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.48204253 0.61995871 0.         0.3965591  0.07381411 0.2578647
 0.61211569 0.75452559 0.63666954 0.4563411 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
# Create two 1D NumPy arrays
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

outer_sub=np.subtract.outer(array_1,array_2)
print(outer_sub)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)