# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
# !pip install numpy


In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

2.3.3


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
vec = np.array([0]*10)
print(vec)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print((vec.size * vec.itemsize))
print(vec.size)
print(vec.itemsize)

80
10
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
ones_vec = np.ones(10)
print(ones_vec)
ones_vec[4]= 0
print(ones_vec)    

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]


In [8]:
vec = np.array([2]*10)
vec[4] = 5
vec

array([2, 2, 2, 2, 5, 2, 2, 2, 2, 2])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
# np.arange(start, stop, step)
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vec = np.array(vec)
print(vec[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
arr = np.array([[1,2,3],[1,2,4],[1,2,3]])
print(arr)

[[1 2 3]
 [1 2 4]
 [1 2 3]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
vec = [1,2,0,0,4,0]
non_zero_indices = [i for i, x in enumerate(vec) if x != 0]
print(non_zero_indices)

[0, 1, 4]


In [13]:
np.nonzero(vec)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random((3,3,3))

array([[[0.32183641, 0.95483441, 0.48067409],
        [0.41502203, 0.28331577, 0.79145643],
        [0.81103073, 0.19516197, 0.2569672 ]],

       [[0.55015883, 0.07835438, 0.33647392],
        [0.28837334, 0.58158538, 0.27419293],
        [0.07386502, 0.41698634, 0.9417047 ]],

       [[0.67457424, 0.77281224, 0.97615832],
        [0.66588228, 0.75421085, 0.05438452],
        [0.13952324, 0.33589379, 0.44541374]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
arr = np.random.random((10,10,10))
print(np.min(arr))
print(np.max(arr))

0.00232612985613756
0.9993145340585026


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
x = np.random.random(10)
print(x)
n= int(len(x))
print(n)
np.mean(x)

[0.85074646 0.48753989 0.60204045 0.47242955 0.79540028 0.91216921
 0.14959141 0.67849435 0.29501823 0.1616758 ]
10


np.float64(0.5405105627336975)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
x = np.ones((5,5))
print(x)
x[1:-1, 1:-1] = 0
print("After bordring \n",x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
After bordring 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
x = np.zeros((8,8), dtype = int)
x[1::2, ::2]=1
x[::2,1::2]=1

x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
# The shape of the array
shape = (6, 7, 8)

linear_index = 98

index = np.unravel_index(linear_index, shape)
print(f"The index is: {index}")

The index is: (np.int64(1), np.int64(5), np.int64(2))


In [24]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
arr = np.zeros(8)
rep = (3,1)
arr = np.tile(arr, (8,1))
arr[1::2, ::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
arr = np.random.random((5,5))
min = arr.min()
max = arr.max()
print("Arr- min", arr-min)
print("Max - Min ", max-min)
normalized_arr = (arr - min) / (max - min)
print("Normalized Array:\n", normalized_arr)

Arr- min [[0.66995184 0.79820476 0.90757968 0.43499482 0.66018501]
 [0.84237588 0.84663312 0.70368627 0.62032296 0.06502021]
 [0.90661994 0.30874967 0.41267085 0.         0.76246274]
 [0.55394931 0.45690217 0.29930265 0.36961233 0.59024719]
 [0.8498361  0.02509825 0.51883259 0.42096544 0.86386847]]
Max - Min  0.9075796781764379
Normalized Array:
 [[0.73817413 0.87948725 1.         0.47929105 0.72741273]
 [0.92815639 0.93284715 0.77534379 0.68349146 0.07164132]
 [0.99894253 0.34019015 0.4546938  0.         0.84010556]
 [0.61035887 0.50342927 0.32978113 0.40725055 0.65035302]
 [0.9363763  0.02765405 0.57166616 0.46383304 0.95183761]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
a = np.ones((5, 3))
b = np.ones((3, 2))

Z = np.matmul(a,b)
print("Z Matrix \n",Z)
print("MAtrix A \n",a)
print("Matrix B \n",b)
print("Matrix Multiplication AxB \n")
print(np.dot(a, b))

Z Matrix 
 [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
MAtrix A 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrix B 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix Multiplication AxB 

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
arr = np.arange(10)
for i in arr:
    if i>3 and i<8:
        arr[i] *= -1
print(arr)
Z  = np.arange(10)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5),-1))
import numpy as np
print(np.sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
Z = np.ones(5)
Z**Z


array([1., 1., 1., 1., 1.])

In [32]:
2 << Z >> 2   # not legal 

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
Z <- Z


In [ ]:
1j*Z


In [ ]:
Z/1/1   


In [ ]:
# Z<Z>Z   not Legal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
np.array(0) / np.array(0)

C:\Program Files\KMSpico\temp\ipykernel_8544\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [34]:
np.array(0) // np.array(0)

C:\Program Files\KMSpico\temp\ipykernel_8544\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [35]:
np.array([np.nan]).astype(int).astype(float)

C:\Program Files\KMSpico\temp\ipykernel_8544\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [36]:
Z = np.random.uniform(0,10,10)
print(Z)

[4.21892302 8.68553881 9.33573842 0.08839914 7.4942925  1.87117673
 8.5641145  7.93621681 9.54280747 0.36643592]


In [37]:
print(np.abs(Z))

[4.21892302 8.68553881 9.33573842 0.08839914 7.4942925  1.87117673
 8.5641145  7.93621681 9.54280747 0.36643592]


In [38]:
print(np.copysign(np.ceil(Z), Z))

[ 5.  9. 10.  1.  8.  2.  9.  8. 10.  1.]


In [39]:
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 5.  9. 10.  1.  8.  2.  9.  8. 10.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [40]:
ar1=  np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,8,9,10])
intersection = np.intersect1d(ar1, arr2)
print(intersection)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [41]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0


In [42]:
_ = np.seterr(**defaults)

In [43]:
z = np.ones(1) / 0
print(z)

[inf]


C:\Program Files\KMSpico\temp\ipykernel_8544\2398573293.py:1: RuntimeWarning: divide by zero encountered in divide
  z = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Program Files\KMSpico\temp\ipykernel_8544\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
import datetime
today = datetime.date.today()   
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)
print("Today:", today, "yesterday:", yesterday, "tomorrow:", tomorrow)

Today: 2025-10-15 yesterday: 2025-10-14 tomorrow: 2025-10-16


In [46]:
today = np.datetime64('now', 'M')
yest = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomor = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yest,today, tomor

(np.datetime64('2025-10-14'),
 np.datetime64('2025-10'),
 np.datetime64('2025-10-16'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
import calendar
y = 2000
m = 8
print(calendar.month(y, m))

    August 2000
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31



In [48]:
Z = np.arange('2016-07', '2016-09', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31' '2016-08-01' '2016-08-02' '2016-08-03' '2016-08-04'
 '2016-08-05' '2016-08-06' '2016-08-07' '2016-08-08' '2016-08-09'
 '2016-08-10' '2016-08-11' '2016-08-12' '2016-08-13' '2016-08-14'
 '2016-08-15' '2016-08-16' '2016-08-17' '2016-08-18' '2016-08-19'
 '2016-08-20' '2016-08-21' '2016-08-22' '2016-08-23' '2016-08-24'
 '2016-08-25' '2016-08-26' '2016-08-27' '2016-08-28' '2016-08-29'
 '2016-08-30' '2016-08-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [49]:
A = np.ones(3)*1
B = B = np.ones(3)*2
print(A)
print(B)

[1. 1. 1.]
[2. 2. 2.]


In [50]:
add = np.add(A,B,out=B)
np.divide(A,2,out=B)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-0.5, -0.5, -0.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [51]:
Z = np.random.uniform(0,10,10)
print(Z)

[0.53179784 4.22561693 4.22813251 5.99887256 3.12091033 6.53444139
 5.43159897 7.69293498 3.9251745  5.89757601]


In [52]:
# Method 1
print(Z-Z%1)
print(np.floor(Z))
print(Z//1)
print(np.trunc(Z))
print(Z.astype(int))

[0. 4. 4. 5. 3. 6. 5. 7. 3. 5.]
[0. 4. 4. 5. 3. 6. 5. 7. 3. 5.]
[0. 4. 4. 5. 3. 6. 5. 7. 3. 5.]
[0. 4. 4. 5. 3. 6. 5. 7. 3. 5.]
[0 4 4 5 3 6 5 7 3 5]


In [53]:
50//3

16

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [54]:
arr = np.zeros((5,5))
print(arr)
print("\n After adding the value from 0-4\n")
arr +=np.arange(5)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 After adding the value from 0-4

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [55]:
iter = ([x for x in range(10)])
iter


np.fromiter(iter, np.float32)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [56]:
x = np.linspace(0, 1, num=10, endpoint=True)
print(x)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [57]:
arr = np.random.random(10)
print(np.sort(arr))
print(np.sort(arr[::-1]))

[0.14643858 0.20972221 0.26482506 0.28710018 0.60207605 0.61043263
 0.67727044 0.77003159 0.78495061 0.83233184]
[0.14643858 0.20972221 0.26482506 0.28710018 0.60207605 0.61043263
 0.67727044 0.77003159 0.78495061 0.83233184]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [58]:
z = np.arange(10)
z = np.add.reduce(z)
print(z)

45


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [59]:
X = np.random.randint(0,2,6)
print(X)
Y = np.random.randint(0,2,6)
print(Y)

print(np.isclose(X,Y))
print(np.allclose(X,Y))

[1 0 0 0 1 0]
[1 1 0 1 1 0]
[ True False  True False  True  True]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [60]:
# Importing the NumPy library and aliasing it as 'np'
import numpy as np

# Creating a NumPy array 'x' filled with zeros, containing 10 elements
x = np.zeros(10)

# Setting the 'writeable' flag of the array 'x' to False, making it read-only
x.flags.writeable = False

# Printing a message to test whether the array is read-only or not
print("Test the array is read-only or not:")

# Attempting to change the value of the first element in the array 'x'
print("Try to change the value of the first element:")
# x[0] = 1  # This line will raise an error since the array is read-only 


Test the array is read-only or not:
Try to change the value of the first element:


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [61]:
z = np.random.random((10, 2))
z
# extracting  the columns into x and y 
x,y = z[:,0], z[:, 1]
# x, y = z[:, 0], z[:, 1]
print(x)
print(y)

[0.89725274 0.93207932 0.78237444 0.6242079  0.81217375 0.2507646
 0.86213809 0.65175825 0.14497835 0.37801628]
[0.94259129 0.47823671 0.76783124 0.66476192 0.09540191 0.86186992
 0.3866018  0.20603352 0.69946473 0.35745191]


In [62]:
# Calculating the Euclidean distance (r) using the formula sqrt(x^2 + y^2)
r = np.sqrt(x**2 + y**2)
print(r)

[1.30136114 1.04760785 1.09620919 0.9118903  0.81775774 0.89760941
 0.9448508  0.68354856 0.7143316  0.5202578 ]


In [63]:
# Calculating the angles (t) using arctan2() function, which returns the arctangent of y/x in radians
t = np.arctan2(y, x)

# Displaying the calculated Euclidean distances (r)
print(r)

# Displaying the calculated angles (t) in radians
print(t)

[1.30136114 1.04760785 1.09620919 0.9118903  0.81775774 0.89760941
 0.9448508  0.68354856 0.7143316  0.5202578 ]
[0.81003578 0.4740614  0.77601697 0.81685013 0.11692907 1.28765903
 0.42154099 0.30617898 1.36641985 0.75744453]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [64]:
vec = np.random.rand(10)
vec

array([0.54573308, 0.55773394, 0.18516315, 0.60946874, 0.3987221 ,
       0.25166065, 0.76716793, 0.81418646, 0.20139925, 0.62092422])

In [65]:
max_val = np.max(vec)
max_val

np.float64(0.8141864591149384)

In [66]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.55794707 0.77020576 0.70158247 0.08049949 0.66360968 0.21906787
 0.83247427 0.5523461  0.38025999 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [67]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [68]:
# Create two 1D NumPy arrays
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

outer_sub=np.subtract.outer(array_1,array_2)
print(outer_sub)

[[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [69]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [70]:
# np.set_printoptions(threshold=float("inf"))
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [71]:
# Creating an array 'x' containing numbers from 0 to 99 using arange() function
x = np.arange(100)

# Displaying the original array 'x'
print("Original array:")
print(x)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [72]:
# genrating the random number for comparison
a = np.random.uniform(0,100)
# Displaying the value used for comparison
print("Value to compare:")
print(a)

Value to compare:
99.89926868039916


In [73]:
(np.abs(x - a))

array([99.89926868, 98.89926868, 97.89926868, 96.89926868, 95.89926868,
       94.89926868, 93.89926868, 92.89926868, 91.89926868, 90.89926868,
       89.89926868, 88.89926868, 87.89926868, 86.89926868, 85.89926868,
       84.89926868, 83.89926868, 82.89926868, 81.89926868, 80.89926868,
       79.89926868, 78.89926868, 77.89926868, 76.89926868, 75.89926868,
       74.89926868, 73.89926868, 72.89926868, 71.89926868, 70.89926868,
       69.89926868, 68.89926868, 67.89926868, 66.89926868, 65.89926868,
       64.89926868, 63.89926868, 62.89926868, 61.89926868, 60.89926868,
       59.89926868, 58.89926868, 57.89926868, 56.89926868, 55.89926868,
       54.89926868, 53.89926868, 52.89926868, 51.89926868, 50.89926868,
       49.89926868, 48.89926868, 47.89926868, 46.89926868, 45.89926868,
       44.89926868, 43.89926868, 42.89926868, 41.89926868, 40.89926868,
       39.89926868, 38.89926868, 37.89926868, 36.89926868, 35.89926868,
       34.89926868, 33.89926868, 32.89926868, 31.89926868, 30.89

In [74]:
index = (np.abs(x - a)).argmin()
print(index)

99


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [75]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [76]:
a = np.random.random((10, 2))
x, y = np.atleast_2d(a[:, 0], a[:, 1])
print(a)

[[0.42730103 0.53305894]
 [0.85681157 0.49053851]
 [0.58627884 0.5852719 ]
 [0.91614846 0.25842603]
 [0.8117694  0.70689643]
 [0.94812377 0.58679241]
 [0.06476153 0.77483189]
 [0.66635503 0.98382123]
 [0.72143095 0.66291115]
 [0.273207   0.26858385]]


In [77]:
d = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)
print(d)

[[0.         0.43161011 0.16733241 0.56070941 0.42194241 0.52358725
  0.43576261 0.51022882 0.32151828 0.30609157]
 [0.43161011 0.         0.28663979 0.23957686 0.22099671 0.13267528
  0.84152599 0.52877361 0.21918083 0.62438623]
 [0.16733241 0.28663979 0.         0.4643729  0.25620016 0.36184813
  0.55489936 0.40651416 0.15586516 0.44531483]
 [0.56070941 0.23957686 0.4643729  0.         0.46045705 0.32991954
  0.99575836 0.76719942 0.44891327 0.64302169]
 [0.42194241 0.22099671 0.25620016 0.46045705 0.         0.18170715
  0.75009066 0.31278216 0.10047757 0.69438274]
 [0.52358725 0.13267528 0.36184813 0.32991954 0.18170715 0.
  0.9031543  0.48685265 0.23913113 0.74616978]
 [0.43576261 0.84152599 0.55489936 0.99575836 0.75009066 0.9031543
  0.         0.63686049 0.66613886 0.54748205]
 [0.51022882 0.52877361 0.40651416 0.76719942 0.31278216 0.48685265
  0.63686049 0.         0.32560196 0.8161678 ]
 [0.32151828 0.21918083 0.15586516 0.44891327 0.10047757 0.23913113
  0.66613886 0.325601

In [78]:
!pip install scipy


In [79]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.62578648 1.02952643 0.10431537 0.70332515 0.8463038
  0.33159897 0.88493297 0.62307155 0.24557085]
 [0.62578648 0.         0.41177772 0.71383541 0.3919387  0.6455455
  0.42776807 0.44542861 0.45675253 0.71300843]
 [1.02952643 0.41177772 0.         1.12180279 0.6604836  0.71548105
  0.77739662 0.39790881 0.77535858 1.07823205]
 [0.10431537 0.71383541 1.12180279 0.         0.74777344 0.94771076
  0.4356179  0.98860536 0.6531057  0.30378506]
 [0.70332515 0.3919387  0.6604836  0.74777344 0.         1.03172252
  0.68724885 0.83083787 0.13349076 0.89219199]
 [0.8463038  0.6455455  0.71548105 0.94771076 1.03172252 0.
  0.52199437 0.31916894 1.06981367 0.71884366]
 [0.33159897 0.42776807 0.77739662 0.4356179  0.68724885 0.52199437
  0.         0.56421194 0.66792711 0.3010491 ]
 [0.88493297 0.44542861 0.39790881 0.98860536 0.83083787 0.31916894
  0.56421194 0.         0.90210338 0.84384008]
 [0.62307155 0.45675253 0.77535858 0.6531057  0.13349076 1.06981367
  0.66792711 0.9021033

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [80]:
x=np.random.randn()
x = x.astype('int64')
print(x.dtype)  
print(x)


AttributeError: 'float' object has no attribute 'astype'

In [ ]:
'''he problem with your code lies in the first line (x = np.random.randn()), as it creates a single random floating-point object, 
and the astype() method cannot be applied to a single float. To fix this, you can create a list of numbers and pass it to the np.array()
function to convert it into an array. Then, you can use the astype() method to change the data type of the array. Here is the corrected code:'''
x=np.random.randn(20)
x = x.astype('int64')
print(x.dtype)  
print(x)

In [ ]:

# create a float (32 bits) array
x = np.array([1.0, 2.0, 3.0], dtype=np.float32)
# convert to an integer (32 bits) array in place
x = x.astype('int32')
print(x.dtype)  
print(x) 

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in enumerate(Z):
    print(f"Index: {index}, Value: {value}")
for index in np.ndindex(Z.shape):
    print(index, Z[index])



In [ ]:
arr = np.array([[1, 2], [3, 4]])

print("Using enumerate():")
for i, row in enumerate(arr):
    print(f"Row {i}: {row}")

print("\nUsing ndenumerate():")
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
# Generating 2D grids 'x' and 'y' using meshgrid with 10 evenly spaced points from -1 to 1
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
# Calculating the Euclidean distance 'd' from the origin using the generated grids 'x' and 'y'
d = np.sqrt(x*x + y*y)
# Defining parameters sigma and mu for a Gaussian-like distribution
sigma, mu = 1.0, 0.0
# Calculating the Gaussian-like distribution 'g' based on the distance 'd', sigma, and mu
g = np.exp(-((d - mu)**2 / (2.0 * sigma**2)))

# Printing a message indicating a 2D Gaussian-like array will be displayed
print("2D Gaussian-like array:")

# Printing the calculated 2D Gaussian-like array 'g'
print(g) 


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
array = np.zeros((4,4))
print("origional array \n", array)
np.put(array, np.random.choice(range(4*4), 4, replace=False ),2.5)
print("array after putting random value \n",array)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
# Displaying the message indicating the original matrix
print("Original matrix:\n")

# Creating a random matrix of size (5, 10)
X = np.random.rand(3, 5)
print(X)
Y = X - X.mean(axis=1, keepdims=True)
mean = X.mean(axis=1,keepdims=True)
print(mean)
print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
print("origional Array\n")
nums = np.random.randint(0,10,(3,3))
print(nums)
print("Sorted array by nth column")
print(nums[nums[:,0].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
print("Origional Array \n")
nums = np.random.randint(0,5,(4,10))
print(nums)
# Cheacking the array has null value or not
print((~nums.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [83]:
# Generating an array of 5 random numbers between 1 and 12 using np.random.uniform()
x = np.random.uniform(1, 12, 5)
print(x)
# Setting a value 'v' to find the number closest to it in the array 'x'
v = 4
# Finding the value 'n' in 'x' that is closest to 'v'
# Using np.abs(x - v).argmin() to get the index of the element in 'x' closest to 'v'
# Accessing the element using x.flat[index] to get the closest value 'n'
n = x.flat[np.abs(x - v).argmin()]

# Printing the value 'n' that is closest to 'v'
print(n) 


[2.43184733 4.57581557 1.34950771 2.46774261 1.81491653]
4.575815569326276


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)